name: Build and Test

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  build-gradle:
    name: Build and test in Gradle
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Restore Gradle caches
        uses: actions/cache@master
        env:
          cache-name: gradle-cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{hashFiles('**/build.gradle') }}
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Run Gradle build and test
        run: ./gradlew clean build
